export default {
  login: "ashus014",
  id: 20342096,
  node_id: "MDQ6VXNlcjIwMzQyMDk2",
  avatar_url: "https://avatars.githubusercontent.com/u/20342096?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ashus014",
  html_url: "https://github.com/ashus014",
  followers_url: "https://api.github.com/users/ashus014/followers",
  following_url: "https://api.github.com/users/ashus014/following{/other_user}",
  gists_url: "https://api.github.com/users/ashus014/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ashus014/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ashus014/subscriptions",
  organizations_url: "https://api.github.com/users/ashus014/orgs",
  repos_url: "https://api.github.com/users/ashus014/repos",
  events_url: "https://api.github.com/users/ashus014/events{/privacy}",
  received_events_url: "https://api.github.com/users/ashus014/received_events",
  type: "User",
  site_admin: false,
  name: "Ashu Singh",
  company: null,
  blog: "",
  location: "London",
  email: null,
  hireable: null,
  bio: "GOD is real unless declared integer.",
  twitter_username: null,
  public_repos: 87,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2016-07-07T16:19:38Z",
  updated_at: "2022-12-21T05:37:07Z",
};
